---
- hosts: all
  user: root

  tasks:
   - name: Install SNAPS-OO
     command: pip install -chttps://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt?h=stable/ocata -e git+https://gerrit.opnfv.org/gerrit/snaps#egg=snaps

   - name: Transfer copy_rc_file.sh
     copy: src=copy_rc_file.sh dest=~/copy_rc_file.sh mode=0777

   - name: Execute copy_rc_file.sh
     command: ~/copy_rc_file.sh

   - name: Execute Tests
     command: python ~/src/snaps/snaps/test_runner.py -e ~/openrc -n public -ci
